# Reload config with 'r'
unbind r
bind p source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Enable True Color
set -sa terminal-overrides "*:Tc"

# Set escape-time
set-option -sg escape-time 10
set-option -g focus-events on

# Use system clipboard
set -g set-clipboard on

# Set prefix to Alt+F
set -g prefix M-d

# Mouse & Keybindings
set -g mouse on
setw -g mode-keys vi

# Prompt for window name
bind t command-prompt "rename-window '%%'"

# Split window bindings
bind | split-window -h
bind _ split-window -v

# Pane Navigation (Vi-like)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick Window Selection
bind q select-window -t 1
bind w select-window -t 2
bind e select-window -t 3
bind r select-window -t 4

# Status Bar Configuration
set-option -g allow-rename off
set -g status on
set -g status-interval 1
set -g status-position top
set -g status-justify centre
set -g status-style "bg=default,fg=#ffffff"

# Left: Session Name (Icon: Gold, Text: Dark Gray)
set -g status-left-length 30
set -g status-left " #[fg=#e5c07b] #[fg=#3e4451,bold]#S #[default] "

# Window List Styling
setw -g window-status-format " #[fg=#3e4451]#I: #W "
setw -g window-status-current-format "#[fg=#e5c07b] #I: #W "

# Right: System Info (Icons: Gold, Text: Dark Gray)
set -g status-right-length 50
set -g status-right " #[fg=#e5c07b] #[fg=#3e4451]%Y-%m-%d #[fg=#e5c07b] #[fg=#3e4451]%H:%M "

# Active & Inactive Window Styling
setw -g window-status-current-style "bg=#3e4451,fg=#ffffff,bold"
setw -g window-status-style "bg=#e5c07b,fg=#abb2bf"

# Start Window & Pane Indexing from 1
set -g base-index 1
set -g renumber-windows on

# Plugin Management
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Automatically save and restore sessions
set -g @resurrect-save 'on'
set -g @resurrect-restore 'on'
set -g @resurrect-save-interval '10'

# Auto-install TPM if not present
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TPM (Keep at the bottom)
run '~/.tmux/plugins/tpm/tpm'
