# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions history-substring-search zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
fi

# Aliases
alias zshconf="mate ~/.zshrc"
alias dotconf="nvim ~/dotfiles"
alias la="ls -a"

# NVIM
export PATH="$PATH:/opt/nvim-linux64/bin"

# fnm
FNM_PATH="$HOME/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$HOME/.local/share/fnm:$PATH"
  eval "`fnm env`"
fi

# Created by `pipx` on 2024-12-17 14:36:38
export PATH="$PATH:/home/ldk/.local/bin"
