# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions history-substring-search zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
fi

# Aliases
alias dotconf="nvim ~/repos/dotfiles"
alias dev="$HOME/repos/dotfiles/scripts/dev.sh"
alias la="ls -a"
alias :q="exit"

# fnm
FNM_PATH="$HOME/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$HOME/.local/share/fnm:$PATH"
  eval "`fnm env`"
fi

# Created by `pipx` on 2024-12-17 14:36:38
export PATH="$HOME/.local/bin:$PATH"
autoload -U compinit; compinit

# Fast Node Manager
FNM_PATH="$HOME/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi

# Neovim (bob)
export PATH="$HOME/.local/share/bob/nvim-bin:$PATH"

# Rust / Cargo
if [ -f "$HOME/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

# Set PI agent dir to dotfiles-managed config
export PI_CODING_AGENT_DIR="/home/kruyerl/repos/dotfiles/configs/pi"

