return {
  --   "mfussenegger/nvim-lint",
  --   opts = {
  --     -- Event to trigger linters
  --     events = { "BufWritePost", "BufReadPost", "InsertLeave" },
  --     linters_by_ft = {
  --       fish = { "fish" },
  --       markdown = { "vale" },
  --       javascript = { "eslint_d" },
  --       typescript = { "eslint_d" },
  --     },
  --     linters = {},
  --   },
  --   {
  --     "williamboman/mason.nvim",
  --     lazy = false,
  --     config = function()
  --       require("mason").setup()
  --     end,
  --   },
  --   {
  --     "williamboman/mason-lspconfig.nvim",
  --     lazy = false,
  --     config = function()
  --       require("mason-lspconfig").setup({
  --         ensure_installed = { "lua_ls", "tsserver", "stylua" },
  --       })
  --     end,
  --   },
}
